#
#
#
#

mySQL:
  username: 'root'
  password: ''
  hostname: 'localhost'
  port: 3306
  database: 'SPAZIORPG'

config:
  default-lang: 'lang_us'
  statistics:
    started-stats:
      mana: 20.0
      life: 20.0
    max-skill:
      strength: 100
      agility: 100
      life: 100
      defense: 100
    increase-per-skill:
      mana: 0.80
      life: 0.80
    