name: SpazioRPG
main: store.j3studios.plugin.spaziorpg.RPG
version: 0.0.1
author: Josn3r
softdepend: [Vault,PlaceholderAPI,WorldGuard,ItemsAdder]
loadBefore: [Vault,PlaceholderAPI,WorldGuard,ItemsAdder]
api-version: 1.16
commands:
  spaziorpg:
  monitor: